# Generated by Django 3.0.5 on 2020-04-28 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_ctration',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 21, 51, 28, 598725), verbose_name='дата обращения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='тема обращения'),
        ),
    ]
