# Generated by Django 3.0.7 on 2020-06-22 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_name', models.CharField(max_length=100, null=True, verbose_name='Ваше имя')),
                ('subscribe_email', models.CharField(max_length=100, verbose_name='Ваш email')),
                ('subscribe_date', models.DateTimeField(default=datetime.datetime(2020, 6, 22, 19, 56, 17, 474292), verbose_name='Дата подписки')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_request_name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('subscribe_request_email', models.CharField(max_length=100, verbose_name='Ваш email')),
                ('subscribe_request_date', models.DateTimeField(default=datetime.datetime(2020, 6, 22, 19, 56, 17, 474292), verbose_name='Дата обращения')),
                ('subscribe_request_text', models.TextField(max_length=10000, verbose_name='Текст обращения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=1000, verbose_name='название тэга')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=1000, null=True, verbose_name='заголовок статьи')),
                ('article_text', models.CharField(max_length=10000, null=True, verbose_name='текст статьи')),
                ('article_text_short', models.CharField(max_length=100, null=True, verbose_name='текст статьи 100 знаков')),
                ('article_date', models.DateTimeField(default=datetime.datetime(2020, 6, 22, 19, 56, 17, 474292), verbose_name='дата публикации статьи')),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='рисунок к статье')),
                ('article_tag', models.ManyToManyField(to='articles.Tag')),
            ],
        ),
    ]
