# Generated by Django 3.0.7 on 2020-06-29 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=1000, null=True, verbose_name='заголовок статьи')),
                ('article_text', models.CharField(max_length=10000, null=True, verbose_name='текст статьи')),
                ('article_text_short', models.CharField(max_length=100, null=True, verbose_name='текст статьи 100 знаков')),
                ('article_date', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 16, 3, 10, 379884), verbose_name='дата публикации статьи')),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='рисунок к статье')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_request_type', models.CharField(choices=[('SP', 'Статобработка'), ('CO', 'Консультация'), ('QS', 'Вопрос'), ('RV', 'Рецензия')], default='SP', max_length=2, verbose_name='Тип запроса')),
                ('subscribe_request_subject', models.CharField(default='', max_length=200, verbose_name='Тема обращения')),
                ('subscribe_request_text', models.TextField(default='', max_length=10000, verbose_name='Текст обращения')),
                ('subscribe_request_date', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 16, 3, 10, 379884), verbose_name='Дата обращения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=1000, verbose_name='название тэга')),
            ],
        ),
    ]
