# Generated by Django 3.0.7 on 2020-06-23 17:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20200623_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 20, 53, 56, 592820), verbose_name='дата публикации статьи'),
        ),
        migrations.AlterField(
            model_name='subscriber_request',
            name='subscribe_request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 20, 53, 56, 837584), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='subscriber_request',
            name='subscribe_request_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
    ]
