# Generated by Django 3.0.7 on 2020-06-25 11:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20200623_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 14, 26, 48, 926429), verbose_name='дата публикации статьи'),
        ),
        migrations.AlterField(
            model_name='subscriber_request',
            name='subscribe_request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 14, 26, 48, 926429), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='subscriber_request',
            name='subscribe_request_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
